### ISSUE TITLE
Question: how to make the BMP conversion permanent?

### ISSUE THREAD

**Issue by Quas7** [jeanthom/stlink-tool#12]
Hi,

I stumbled accros this tool although I own already a few BMP blue-pills and an original BMP.
But I really like the idea of quickly converting my pile of cheap cloned stlinks to BMPs. ;)

Is there a known good way to make the conversion permanent with maybe a second flashing step?
Thank you.

**Comment by jeanthom** [comment]
Hi,

I started thinkering with that idea in DirtyJTAG (https://github.com/jeanthom/DirtyJTAG/pull/43) but haven't been able to deliver something working. I hope to gain enough motivation in the months to come to start working again on that feature.

You can otherwise do it [Lujji style](https://lujji.github.io/blog/installing-blackmagic-via-stlink-bootloader/) and have a udev rule to automatically exit the bootloader when your ST-Link dongle is plugged in.

**Comment by Quas7** [comment]
Alright, thanks for the feedback. I just wanted to make sure I did not miss something easy and obvious but it seems to be quite the opposite. ;)
