### ISSUE TITLE
DirtyJTAG cannot be flashed via DFU after being flashed via SWD?

### ISSUE THREAD

**Issue by brainstorm** [jeanthom/stlink-tool#13]
I was going to flash my already-flashed DirtyJTAG probe with `stlink-tool` but was never found after re-plugging it several times:

```
$ ../../stlink-tool-dirtyjtag/stlink-tool -p dirtyjtag.stlinkv2dfu.bin
No ST-Link in DFU mode found. Replug ST-Link to flash!
``` 

Then I realised that the VID:PID does not match with any of those from [main.c](https://github.com/jeanthom/stlink-tool/blob/master/src/main.c#L29):

```
Bus 020 Device 023: ID 1209:c0ca 1209 DirtyJTAG  Serial: 8B83070132124647524B4E00
```

So I guess I'll go back opening the probe and connecting the internal SWD wires unless there's another more straightforward way to flash it? Would it suffice adding that DirtyJTAG VID:PID ids above to the the existing list as Uwe comments on PR https://github.com/jeanthom/stlink-tool/pull/11 ?

**Comment by jeanthom** [comment]
Hi! stlink-tool is a tool meant to reprogram devices which are flashed with the ST-Link bootloader. This bootloader is stored in flash and will be erased whenever you flash something else via SWD.

I'm thinking of two reasons for why your dongle is recognized directly as a DirtyJTAG dongle:
 * You flashed your dongle via SWD and have erased the ST-Link bootloader
 * You still have the original bootloader, but you're automatically bypass it using a [udev rule](https://lujji.github.io/blog/installing-blackmagic-via-stlink-bootloader/) which you need to remove in order to use stlink-tool

Please do note that using stlink-tool for installing DirtyJTAG is currently not recommended (https://github.com/jeanthom/DirtyJTAG/issues/52), and in DirtyJTAG 2.0 you'll be able to seamlessly use a USB bootloader.

**Comment by brainstorm** [comment]
Yes, I had to go back to the SWD way which is how I flashed the dongle initially... thanks for all the explanation and pointers, it makes more sense now. I'm on OSX, so no udev rules here ;)

Will you be using MCUboot on DirtyJTAG 2.0?: https://github.com/mcu-tools/mcuboot
